/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ApiService } from './services/api.service';
import { SystemService } from './services/system.service';
import { MessageService } from './services/message.service';
import { DeviceService } from './services/device.service';
import { AuthService } from './services/auth.service';
import { ApplicationService } from './services/application.service';
import { DomainService } from './services/domain.service';
import { ProductService } from './services/product.service';
import { PranchetaService } from './services/prancheta.service';
import { UserService } from './services/user.service';
import { PhotoService } from './services/photo.service';
import { FileExplorerService } from './services/file-explorer.service';
import { CadastroService } from './services/cadastro.service';
import { PessoaService } from './services/pessoa.service';
import { OrganizacaoService } from './services/organizacao.service';
import { FormsService } from './services/forms.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ApiService,
    SystemService,
    MessageService,
    DeviceService,
    AuthService,
    ApplicationService,
    DomainService,
    ProductService,
    PranchetaService,
    UserService,
    PhotoService,
    FileExplorerService,
    CadastroService,
    PessoaService,
    OrganizacaoService,
    FormsService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
