/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiService } from './services/api.service';
export { SystemService } from './services/system.service';
export { DeviceService } from './services/device.service';
export { MessageService } from './services/message.service';
export { AuthService } from './services/auth.service';
export { ApplicationService } from './services/application.service';
export { DomainService } from './services/domain.service';
export { ContactsService } from './services/contacts.service';
export { ChamadaService } from './services/chamada.service';
export { ProductService } from './services/product.service';
export { PranchetaService } from './services/prancheta.service';
export { UserService } from './services/user.service';
export { PhotoService } from './services/photo.service';
export { FileExplorerService } from './services/file-explorer.service';
export { VideoService } from './services/video.service';
export { CadastroService } from './services/cadastro.service';
export { EnderecoService } from './services/endereco.service';
export { InformacaoContatoService } from './services/informacao-contato.service';
export { PessoaService } from './services/pessoa.service';
export { UnidadeMedidaService } from './services/unidade-medida.service';
export { PaisService } from './services/pais.service';
export { OrganizacaoService } from './services/organizacao.service';
export { FormsService } from './services/forms.service';
