/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface AcessoPayload {
  bearer?: string;
  chaveAcesso?: string;
  identificacao?: string;
  password?: string;
  refreshToken?: string;
  solicitarSessao?: string;
  user?: User;
}
