/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Form {
  createdAt?: string | null;
  createdBy?: {
} | null;
  description?: string | null;
  internalId?: string | null;
  lastModifiedAt?: string | null;
  lastModifiedBy?: {
} | null;
  tenants?: Array<string> | null;
  title?: string | null;
}
