/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Payload {
  by?: string | null;
  data?: {
} | null;
  equals?: string | null;
  fields?: Array<string> | null;
}
