/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObterListaInformacaoContato } from '../../models/obter-lista-informacao-contato';
import { SyncPayloadDaoInformacaoContato } from '../../models/sync-payload-dao-informacao-contato';

export interface InformacaoContatoGet$Params {
      body: ObterListaInformacaoContato
}

export function informacaoContatoGet(http: HttpClient, rootUrl: string, params: InformacaoContatoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SyncPayloadDaoInformacaoContato>> {
  const rb = new RequestBuilder(rootUrl, informacaoContatoGet.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SyncPayloadDaoInformacaoContato>;
    })
  );
}

informacaoContatoGet.PATH = '/InformacaoContato/Get';
