/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface AcessoPayload {
  bearer?: string | null;
  chaveAcesso?: string | null;
  identificacao?: string | null;
  mode?: string | null;
  password?: string | null;
  refreshToken?: string | null;
  solicitarSessao?: string | null;
  user?: User | null;
}
