/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CardOption } from '../models/card-option';
export interface Card {
  componentName?: string | null;
  componentVersion?: string | null;
  settings?: CardOption | null;
}
