/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CpuInfo {
  external?: number | null;
  heapTotal?: number | null;
  heapUsed?: number | null;
  moment?: string | null;
  rss?: number | null;
  system?: number | null;
  user?: number | null;
}
