/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhoneNumber } from '../models/phone-number';
export interface DevicePayload {
  applicationId?: string | null;
  authentication?: string | null;
  id?: string | null;
  model?: string | null;
  name?: string | null;
  numbers?: Array<PhoneNumber> | null;
}
