/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Domain {
  aplications?: Array<Array<any>> | null;
  createdAt?: string | null;
  createdBy?: {
} | null;
  hostname?: string | null;
  internalId?: string | null;
  lastModifiedAt?: string | null;
  lastModifiedBy?: {
} | null;
  tenants?: Array<string> | null;
  varified?: boolean | null;
}
