/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Domain {
  aplications?: Array<Array<any>> | null;
  hostname?: string | null;
  id?: string | null;
}
