/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Endereco {
  address?: string | null;
  addressNumber?: string | null;
  complement?: string | null;
  createdAt?: Date | null;
  createdBy?: {
} | null;
  internalId?: string | null;
  lastModifiedAt?: Date | null;
  lastModifiedBy?: {
} | null;
  logradouro?: string | null;
  province?: string | null;
  tenants?: Array<string> | null;
}
