/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FiendClientByPayload {

  /**
   * Text of search Clients Disposes to send Message
   */
  cellPhone: string;

  /**
   * Text of search Clients Disposes to send Message
   */
  documentId: string;

  /**
   * Text of search Clients Disposes to send Message
   */
  search: string;

  /**
   * Text of search Clients Disposes to send Message
   */
  username: string;
}
