/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FormCotrollerGetInputDto {
  orderBy?: {
} | null;
  skip?: number | null;
  take?: number | null;
  where?: {
} | null;
}
