/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Perguntas } from '../models/perguntas';
export interface Form {
  createdAt?: Date | null;
  createdBy?: {
} | null;
  description?: string | null;
  internalId?: string | null;
  lastModifiedAt?: Date | null;
  lastModifiedBy?: {
} | null;
  perguntas?: Perguntas | null;
  tenants?: Array<string> | null;
  title?: string | null;
}
