/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InformacaoContato {
  createdAt?: string | null;
  createdBy?: {
} | null;
  description?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  internalId?: string | null;
  lastModifiedAt?: string | null;
  lastModifiedBy?: {
} | null;
  linkedin?: string | null;
  name?: string | null;
  phoneNumber?: string | null;
  tenants?: Array<string> | null;
  tiktok?: string | null;
  whatsAppNumber?: string | null;
}
