/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Marca {
  code?: string | null;
  createdAt?: Date | null;
  createdBy?: {
} | null;
  description?: string | null;
  internalId?: string | null;
  lastModifiedAt?: Date | null;
  lastModifiedBy?: {
} | null;
  name?: string | null;
  siteUrl?: string | null;
  tenants?: Array<string> | null;
}
