/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Organizacao } from '../models/organizacao';
export interface OrganizacaoSyncPayload {
  data: Organizacao;
}
