/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Pessoa } from '../models/pessoa';
import { Photo } from '../models/photo';
import { Tenant } from '../models/tenant';
export interface Organizacao {
  cadastroPessoa?: Pessoa | null;
  createdAt?: string | null;
  createdBy?: {
} | null;
  internalId?: string | null;
  lastModifiedAt?: string | null;
  lastModifiedBy?: {
} | null;

  /**
   * Logomarca da Organização
   */
  logo?: Photo | null;

  /**
   * Nome da Organização
   */
  organizatioName?: string | null;
  tenant?: Tenant | null;
  tenants?: Array<string> | null;
}
