/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Pais {
  createdAt?: Date | null;
  createdBy?: {
} | null;
  ibgeCode: string;
  internalId?: string | null;
  internationaName: string;
  lastModifiedAt?: Date | null;
  lastModifiedBy?: {
} | null;
  nome: string;
  referenciasExternas: Array<string>;
  tenants?: Array<string> | null;
}
