/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PartPayloadDto {
  TotalParts?: number | null;
  currentPart?: number | null;
  md5Full?: string | null;
  md5Part?: string | null;
  partialBase64?: string | null;
}
