/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Pergunta } from '../models/pergunta';
export interface Perguntas {
  perguntas?: Array<Pergunta> | null;
}
