/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Option } from '../models/option';
export interface Pergunta {
  options?: Array<Option> | null;
  questao?: string | null;
  type?: string | null;
}
