/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentoIdentificacao } from '../models/documento-identificacao';
import { Endereco } from '../models/endereco';
export interface Pessoa {
  createdAt?: Date | null;
  createdBy?: {
} | null;
  documentos?: Array<DocumentoIdentificacao> | null;
  emailPessoal?: string | null;
  empresa?: string | null;
  endereco?: Array<Endereco> | null;
  informacoesContato?: Array<string> | null;
  internalId?: string | null;
  lastModifiedAt?: Date | null;
  lastModifiedBy?: {
} | null;

  /**
   * Nome
   */
  nome?: string | null;
  nomeFantasia?: string | null;
  razaoSocial?: string | null;
  registroGeralRepublicaBrasileira?: string | null;
  registroGeralRepublicaBrasileiraOrgaoEmissorOrgaoEmissor: string;
  site?: string | null;

  /**
   * Sobrenome
   */
  sobrenome?: string | null;
  tenants?: Array<string> | null;
  tipoJuridico?: string | null;
}
