/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Prancheta } from '../models/prancheta';
export interface PranchetaSyncPayloadDto {
  defaultGlobalCode?: string;
  prancheta?: Prancheta | null;
}
