/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Card } from '../models/card';
export interface Prancheta {
  cards?: Array<Card> | null;
  createdAt?: string | null;
  createdBy?: {
} | null;
  internalId?: string | null;
  lastModifiedAt?: string | null;
  lastModifiedBy?: {
} | null;
  layout?: string | null;
  order?: number | null;
  tenants?: Array<string> | null;
  title?: string | null;
}
