/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Marca } from '../models/marca';
export interface Product {
  codigoBarras?: string | null;
  codigoFabricanete?: string | null;
  createdAt?: string | null;
  createdBy?: {
} | null;
  description?: string | null;
  gtin?: string | null;
  internalId?: string | null;
  lastModifiedAt?: string | null;
  lastModifiedBy?: {
} | null;
  marca?: Marca | null;
  nossoCodigo?: string | null;
  shortDescription?: string | null;
  sku?: string | null;
  subGrupo?: string | null;
  tenants?: Array<string> | null;

  /**
   * URL do site
   */
  urlWebsiteOficial?: string | null;
}
