/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReadDirectoryOutput {
  isDirectory?: boolean | null;
  isFIFO?: boolean | null;
  isFile?: boolean | null;
  isSocket?: boolean | null;
  isSymbolicLink?: boolean | null;
  name?: string | null;
  path?: string | null;
}
