/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrarInputDto {
  email?: string | null;
  identificacao?: string | null;
  password?: string | null;
  phone?: string | null;
}
