/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InformacaoContato } from '../models/informacao-contato';
export interface SyncPayloadDaoInformacaoContato {
  data: InformacaoContato;
}
