/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UnidadeMedida } from '../models/unidade-medida';
export interface SyncPayloadDaoUnidadeMedida {
  data: UnidadeMedida;
}
