/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Endereco } from '../models/endereco';
export interface SyncPayloadDaoEndereco {
  data: Endereco;
}
