/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TipoDocumentoIdentificacao {
  createdAt?: Date | null;
  createdBy?: {
} | null;

  /**
   * Descrição
   */
  description?: string | null;
  internalId?: string | null;
  lastModifiedAt?: Date | null;
  lastModifiedBy?: {
} | null;
  tenants?: Array<string> | null;
}
