/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UnidadeMedida {
  description?: string | null;
  externalReferenceUrl?: Array<string> | null;
  internationalCode?: string | null;
  name?: string | null;
}
