/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { enderecoGet } from '../fn/endereco/endereco-get';
import { EnderecoGet$Params } from '../fn/endereco/endereco-get';
import { enderecoSync } from '../fn/endereco/endereco-sync';
import { EnderecoSync$Params } from '../fn/endereco/endereco-sync';
import { SyncPayloadDaoEndereco } from '../models/sync-payload-dao-endereco';

@Injectable({ providedIn: 'root' })
export class EnderecoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `enderecoSync()` */
  static readonly EnderecoSyncPath = '/Endereco/Sync';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `enderecoSync()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  enderecoSync$Response(params: EnderecoSync$Params, context?: HttpContext): Observable<StrictHttpResponse<SyncPayloadDaoEndereco>> {
    return enderecoSync(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `enderecoSync$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  enderecoSync(params: EnderecoSync$Params, context?: HttpContext): Observable<SyncPayloadDaoEndereco> {
    return this.enderecoSync$Response(params, context).pipe(
      map((r: StrictHttpResponse<SyncPayloadDaoEndereco>): SyncPayloadDaoEndereco => r.body)
    );
  }

  /** Path part for operation `enderecoGet()` */
  static readonly EnderecoGetPath = '/Endereco/Get';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `enderecoGet()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  enderecoGet$Response(params: EnderecoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SyncPayloadDaoEndereco>> {
    return enderecoGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `enderecoGet$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  enderecoGet(params: EnderecoGet$Params, context?: HttpContext): Observable<SyncPayloadDaoEndereco> {
    return this.enderecoGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<SyncPayloadDaoEndereco>): SyncPayloadDaoEndereco => r.body)
    );
  }

}
