/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { informacaoContatoGet } from '../fn/informacao-contato/informacao-contato-get';
import { InformacaoContatoGet$Params } from '../fn/informacao-contato/informacao-contato-get';
import { informacaoContatoSync } from '../fn/informacao-contato/informacao-contato-sync';
import { InformacaoContatoSync$Params } from '../fn/informacao-contato/informacao-contato-sync';
import { SyncPayloadDaoInformacaoContato } from '../models/sync-payload-dao-informacao-contato';

@Injectable({ providedIn: 'root' })
export class InformacaoContatoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `informacaoContatoSync()` */
  static readonly InformacaoContatoSyncPath = '/InformacaoContato/Sync';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `informacaoContatoSync()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  informacaoContatoSync$Response(params: InformacaoContatoSync$Params, context?: HttpContext): Observable<StrictHttpResponse<SyncPayloadDaoInformacaoContato>> {
    return informacaoContatoSync(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `informacaoContatoSync$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  informacaoContatoSync(params: InformacaoContatoSync$Params, context?: HttpContext): Observable<SyncPayloadDaoInformacaoContato> {
    return this.informacaoContatoSync$Response(params, context).pipe(
      map((r: StrictHttpResponse<SyncPayloadDaoInformacaoContato>): SyncPayloadDaoInformacaoContato => r.body)
    );
  }

  /** Path part for operation `informacaoContatoGet()` */
  static readonly InformacaoContatoGetPath = '/InformacaoContato/Get';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `informacaoContatoGet()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  informacaoContatoGet$Response(params: InformacaoContatoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SyncPayloadDaoInformacaoContato>> {
    return informacaoContatoGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `informacaoContatoGet$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  informacaoContatoGet(params: InformacaoContatoGet$Params, context?: HttpContext): Observable<SyncPayloadDaoInformacaoContato> {
    return this.informacaoContatoGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<SyncPayloadDaoInformacaoContato>): SyncPayloadDaoInformacaoContato => r.body)
    );
  }

}
